#ifndef ROBOT
#define ROBOT


    // initalizes optical sensor
    bool initOPT(int opticalSDA, int opticalSCL, int opticalReadyPin);

    // read from laptop via Bluetooth. Data consists of g-code commands for motor controls and absolute positions generated by openCV
    void readBT();

    // update positions continuously after finishing a g-code execution or after obtaining CV absolute position
    void setPosRobot();
    void setPosOptical(); 

    // compare sensor's position to expected position and check error difference
    void checkForError();

    // g-code exeuction --- (x,y) specifies endpoints. (i,j) specifies arc's center point
    void executeG1(int x, int y); // straight line motion, tells the motor to move to pos X, Y
    void executeG2(int x, int y, int i, int j) ; // clockwise circular arc motion
    void executeG3(int x, int y, int i, int j); // counter-clockwise circular motion

    // --- TOOLS ---
    void setMarker(bool down);   
    void setEraser(bool down);

    void moveRelativePos(float x, float y); 
    void moveAbsPos(float x, float y);
    void stop(); 


    int distToSteps(float dist); // convert travel distance to motor's steps


#endif